pbkit/pbkit

- cli/pollapo/cmds/why.ts
- cli/pollapo/entrypoint.ts
- why command를 추가했습니다.
- 간단한 cycle detection
- print depth 옵션 등이 있습니다.
#7
> [WEB-241] why command

- cli/pollapo/misc/github.ts
- Fix home(userprofile) path using ```getHomeDir``` in config
- Tested on Windows 10 Version 2004 Build 19041.906
resolve #10
> [fix/gh-config-path] Fix bug related w/ github-api-key (#10)

- core/runtime/Long.ts
> [feature/long] Implement long

- cli/pollapo/misc/github-auth.ts
> fix(login): Create directory for hosts file when it is not exist

- cli/pollapo/cmds/login.ts
- cli/pollapo/misc/github-auth.ts
- Add spinner to visualize polling status
- Fix error handling logic to detect error when opening in browser
resolve #24 #23
> fix(login): Enhance pollapo login logic

- cli/pollapo/cmds/add.ts
- cli/pollapo/cmds/remove.ts
- cli/pollapo/entrypoint.ts
pollapo remove command 추가
- User/Repo(@Revision?) 형태로 타겟 입력 가능
- Revision 없으면 User/Repo 같은 dependency 모두 제거
- Revision 있으면 User/Repo@Revision 같은 dependency 제거
- 제거 후 정렬 처리
[#35](https://github.com/riiid/pbkit/issues/35)
> Feat(pollapo): Add remove command

- core/schema/eval-ast-constant.test.ts
- core/schema/eval-ast-constant.ts
string literal eval 구현
- hex string convert to hex
- octal string convert to octal
- special char string convert to special char
- other char just return
Notthing
> Feat(core): Implement eval string literal

- core/parser/proto.regression.test.ts
- core/parser/proto.ts
> fix #39 issue

- core/parser/proto.ts
> Allow prefix _

- cli/pollapo/cmds/add.ts
- cli/pollapo/cmds/install.ts
- cli/pollapo/docs/en/getting-started.md
- cli/pollapo/docs/ko/getting-started.md
> create file if not exists

- .gitignore
- cli/pollapo/cmds/install.ts
- cli/pollapo/cmds/why.ts
- cli/pollapo/pollapoYml.ts
- misc/github/index.ts
> add github hot found error handling

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
> Add Codespace support

- .github/workflows/pollapo-build-macos-binary.yml
> Add macos binary builder

- .github/workflows/pollapo-build-linux-binary.yml
> Add Linux Binary Builder

- cli/pollapo/docs/en/getting-started.md
- cli/pollapo/docs/ko/getting-started.md
> Change installation Guide

- codegen/ts/messages.ts
```protobuf
// test.proto
syntax = "proto3";
package test;
message TestOneof {
oneof MyOneof_1 {
Oneof_1 v1 = 1;
Oneof_2 v2 = 2;
Oneof_3 v3 = 3;
}
oneof MyOneof_2 {
Oneof_1 v1 = 4;
Oneof_2 v2 = 5;
Oneof_3 v3 = 6;
}
}
message Oneof_1 {
string value = 1;
}
message Oneof_2 {
int64 value = 1;
}
message Oneof_3 {
map<string, int64> value = 1;
}
```
```typescript
// out/messages/test/TestOneof.ts
const fieldNames: Map<number, string> = new Map([ // <-- THE PROBLEM
[1, "v1"],
[2, "v2"],
[3, "v3"],
[4, "v1"],
[5, "v2"],
[6, "v3"],
]);
export function decodeBinary(binary: Uint8Array): Type {
const result = getDefaultValue();
const wireMessage = deserialize(binary);
const wireFields = new Map(wireMessage);
const wireFieldNumbers = Array.from(wireFields.keys()).reverse();
oneof: {
const …
```
> [pb] oneof 필드를 ts로 변환할 때 field 필드가 생성되지 않는 현상 수정

- core/parser/proto.ts
> fix pattern

- core/parser/proto.regression.test.ts
- core/parser/proto.ts
> fix aggregate syntax

- codegen/ts/services.ts
> feat: Implement major scenario of createServiceClient

- cli/pb/entrypoint.ts
- cli/pollapo/docs/en/getting-started.md
- cli/pollapo/docs/ko/getting-started.md
- cli/pollapo/entrypoint.ts
> Add completions command for pollapo, pb

- cli/pb/entrypoint.ts
- cli/pollapo/entrypoint.ts
> Add help command for pb, pollapo

- cli/pb/cmds/gen/index.ts
- cli/pb/entrypoint.ts
- cli/pollapo/entrypoint.ts
> Enable did-you-mean support for invalid command

- .vim/coc-settings.json
> Neovim user involved

- .github/workflows/pollapo-build-linux-binary.yml
Change the name binary to pollapo-linux because it is not a binary that only runs on ubuntu.
> :truck: rename pollapo-ubuntu to pollapo-linux

- core/parser/proto.ts
Ref.
https://github.com/protocolbuffers/protobuf/blob/69b0a78315b464e6d4b1b87845cab409cc87dfe7/src/google/protobuf/io/tokenizer.cc#L158-L187
Closes #104
> [#104] Fix Parser Error

- codegen/ts/services.ts
Service의 동작과 function overloading이 다른 점을 수정합니다.
Co-authored-by: Jaewon Ahn <jaewon.ahn@riiid.co>
> Fix wrong function overloading on codegen/ts/services

- codegen/ts/services.ts
methodDescriptor을 type casting하여 type error를 없앱니다.
> cast methodDescriptor

- core/runtime/client-devtools.ts
https://github.com/pbkit/pbkit-devtools/pull/8 에 필요한 configId를 Event에 붙여서 보내줍니다.
> Add configId to devtoolsConfig and ship it on event

- cli/pollapo/docs/en/getting-started.md
> Add installation method to pollapo readme

- cli/pollapo/entrypoint.ts
> :sparkles: add version command

- codegen/ts/index.ts
- codegen/ts/messages.ts
- core/runtime/json/scalar.ts
> Implement decodeJson

- language-server/json-rpc.ts
Update to fix typing error of NotificationMessage
> Update version of json-rpc from 6.0.0 to 8.0.0-next.6

- language-server/base-protocol.test.ts
- language-server/base-protocol.ts
- language-server/json-rpc.ts
- Add test codes for language-server/base-protocol
- Fix base-protocol/writeBaseProtocolMessage
> fix(language-server/base-protocol): Fix writeBaseProtocolMessage and Add test codes

- language-server/base-protocol.test.ts
- language-server/base-protocol.ts
- language-server/json-rpc.test.ts
- language-server/json-rpc.ts
- Add request, notification handler
- Add test codes for handling request, notification
> fix(language-server/jsonrpc-handler): Handle request, notification and Add tests

- core/schema/gotoDefinition.ts
- language-server/lsp.ts
- language-server/server.ts
- Show type information when hover type of field
> feat(lsp/hover): Show type information (type of enum/message) when hover

- core/schema/gotoDefinition.ts
- https://github.com/pbkit/pbkit/issues/159
- https://github.com/pbkit/vscode-pbkit/issues/2
> go to definition for import statement

- cli/pollapo/cmds/install.ts
Install concurrently
ensureDir의 영향이 더 커보이는데, 대안이 없어서 그대로 남겨둠.
> Improve pollapo install performance

- cli/pb/cmds/lsp/index.ts
- core/schema/gotoDefinition.ts
- language-server/server.ts
> Fix typo and Add early return on hover

- core/schema/gotoDefinition.ts
> fix(lsp/gotodef): Fix double-clicked case

- node/save.js
> fix(node): Fix buffer overflow error in `node/save.js`

- codegen/ts/messages.ts
```sh
pb gen ts -o out google/protobuf/map_lite_unittest.proto
```
```sh
diff -u out-before/messages/protobuf_unittest/TestMapLite.ts \
out-after/messages/protobuf_unittest/TestMapLite.ts \
> out.diff
```
```diff
--- out-before/messages/protobuf_unittest/TestMapLite.ts
+++ out-after/messages/protobuf_unittest/TestMapLite.ts
@@ -1,16 +1,14 @@
import {
Type as MapEnumLite,
+  name2num,
+  num2name,
+} from "./MapEnumLite.ts";
+import {
+  Type as ForeignMessageLite,
encodeJson as encodeJson_1,
decodeJson as decodeJson_1,
encodeBinary as encodeBinary_1,
decodeBinary as decodeBinary_1,
-} from "./MapEnumLite.ts";
-import {
-  Type as ForeignMessageLite,
-  encodeJson as encodeJson_2,
-  decodeJson as decodeJson_2,
-  encodeBinary as encodeBinary_2,
-  decodeBinary as decodeBinary_2,
} from …
```
> fix ts codegen bug when generating map field for enum value

- codegen/ts/index.ts
- codegen/ts/messages.ts
- codegen/ts/services.ts
bugfix for [daangn/karrotmesh](https://github.com/daangn/karrotmesh)
> don't specialize well-knowns in service codegen

- compat/protoc/file-descriptor-set.ts
- https://github.com/pbkit/pbkit/issues/140
- https://github.com/pbkit/pbkit/issues/206
> Add `convertSchemaToFileDescriptorSet` function

- misc/github/index.ts
Closes #184 
It works on my windows machine
> fix: access GitHub config location correctly

- codegen/swift/messages.ts
- codegen/swift/services.ts
tested in https://github.com/pbkit/wrp-swift/commit/58c8299a742303267062f5ca37894dce28fcc789
> codegen(swift/wrp-client): Add codegen for wrp-client

- cli/pollapo/cmds/install.ts
- cli/pollapo/pollapoYml.ts
> pollapo: Remove unused codes

- codegen/ts/messages.ts
> Add JSDoc for deprecated type

- README.md
> docs: Remove loc counter

- codegen/swift/services.ts
WrpServiceProdiver -> WrpServiceProvider
> 🐛 typo in swift code generator

- compat/protoc/text-format.ts
- Print repeated scalar values (packed default in proto3)
- Print repeated enum values (packed default in proto3)
> fix(protoc/text-format): Print repeated scalar values / enums field correctly for pbtxt

- scripts/build-npm-packages/buildCore.ts
stop esbuild's child process after the build is done
> build/npm: stop esbuild after build done

- cli/pb/cmds/gen/cmds/protoc-plugin.ts
- cli/pb/cmds/gen/index.ts
- generated/messages/google/protobuf/compiler/(CodeGeneratorResponse)/Feature.ts
- generated/messages/google/protobuf/compiler/(CodeGeneratorResponse)/File.ts
- generated/messages/google/protobuf/compiler/(CodeGeneratorResponse)/index.ts
- generated/messages/google/protobuf/compiler/CodeGeneratorRequest.ts
- generated/messages/google/protobuf/compiler/CodeGeneratorResponse.ts
- generated/messages/google/protobuf/compiler/Version.ts
- generated/messages/google/protobuf/compiler/index.ts
- generated/messages/google/protobuf/index.ts
- scripts/generate.sh
> compat(protoc-plugin): Supports protoc plugins

- cli/pb/cmds/devtools/index.ts
- cli/pb/entrypoint.ts
- core/runtime/client-devtools.ts
related to https://github.com/pbkit/pbkit-devtools/pull/27
> draft: Add standalone devtools cli

- codegen/kt/wrp.ts
TODO: Use import buffer if there is more chance to check imports dynamically.
> fix(codegen/wrp-kt): remove unused import (receivechannel)

- docs/en/README.md
- docs/ko/README.md
> Remove unused docs directory

- cli/pb/cmds/decode/cmds/file-descriptor-set.ts
- cli/pb/cmds/decode/cmds/raw.ts
- cli/pb/cmds/decode/index.ts
- cli/pb/cmds/devtools/index.ts
- cli/pb/cmds/gen/cmds/file-descriptor-set.ts
- cli/pb/cmds/gen/cmds/protoc-plugin.ts
- cli/pb/cmds/gen/cmds/schema.ts
- cli/pb/cmds/gen/cmds/swift/index.ts
- cli/pb/cmds/gen/cmds/ts/cmds/bundle.ts
- cli/pb/cmds/gen/cmds/ts/index.ts
- cli/pb/cmds/gen/cmds/wrp-kt/index.ts
- cli/pb/cmds/gen/index.ts
- cli/pb/cmds/lsp/index.ts
- cli/pb/cmds/vendor/cmds/directory.ts
- cli/pb/cmds/vendor/cmds/install.ts
- cli/pb/cmds/vendor/index.ts
- cli/pb/entrypoint.ts
- cli/pbkit/cmds/download.ts
- cli/pbkit/cmds/list.ts
- cli/pbkit/cmds/remove.ts
- cli/pbkit/cmds/use.ts
- cli/pbkit/entrypoint.ts
- cli/pollapo/cmds/add.ts
- cli/pollapo/cmds/install.ts
- cli/pollapo/cmds/login/index.ts
- cli/pollapo/cmds/login/token.ts
- cli/pollapo/cmds/remove.ts
- cli/pollapo/cmds/why.ts
- cli/pollapo/entrypoint.ts
> Update cliffy version

- cli/pb/cmds/gen/cmds/file-descriptor-set.ts
- cli/pb/cmds/gen/cmds/protoc-plugin.ts
- cli/pb/cmds/gen/cmds/schema.ts
- compat/protoc/file-descriptor-set/fds2pbkit.ts
- compat/protoc/file-descriptor-set/index.ts
- compat/protoc/file-descriptor-set/pbkit2fds.ts
> Add function for converting `FileDescriptorSet` to pbkit `Schema`

- core/ast/extensions-and-reserved.ts
- core/ast/index.ts
- core/ast/lexical-elements.ts
- core/ast/textproto.ts
- core/parser/misc.ts
- core/parser/proto.ts
- core/parser/textproto.ts
- core/visitor/index.ts
> Text format parser

- language-server/json-rpc.ts
- misc/archive/zip.ts
> Pinning esm.sh version for invalidating deps cache

- core/parser/textproto.ts
- language-server/json-rpc.ts
- misc/archive/zip.ts
- scripts/build-npm-packages/buildPbCli.ts
Update dnt to fix this: https://github.com/denoland/dnt/pull/184
> Fix dnt by pinning with query parameter

- core/ast/extensions-and-reserved.ts
- core/parser/proto.ts
> make fieldOption acceptable for extension

- core/ast/index.ts
- core/parser/proto.ts
- core/visitor/index.ts
https://github.com/pbkit/vscode-pbkit/issues/24
> parse edition syntax
