pbkit/pbkit

cli/pollapo/misc/github.ts

pollapo login이 되지 않은 상태에서 pollapo install을 실행할 경우 뜨는 에러 메시지를 좀 더 구체화합니다.

Edit PollapoNotLoggedInError message

---

codegen/ts/messages.ts

Since `WireType.LengthDelimited` is infered as `WireType` (expected `WireType.LengthDelimited`), so the return value is infered as `{ type: WireType; value: Uint8Array}`  (expected `LengthDelimited`).
It fixes above issue.

Fix typing issue

---

codegen/ts/messages.ts

`pb gen ts`를 이용하여 `Struct.proto`를 컴파일 할 경우, `out/messages/google/protobuf/Struct.ts`에 다음과 같은 코드가 생성됩니다:
```typescript
export function encodeBinary(value: Type): Uint8Array {
const result: WireMessage = [];
for (const [key, value] of Object.entries(value.fields)) { // variable shadowing
result.push(
[1, { type: WireType.LengthDelimited as const, value: serialize([[1, tsValueToWireValueFns.string(key)], [2, { type: WireType.LengthDelimited as const, value: encodeBinary_1(value) }]]) }],
);
}
return serialize(result);
}
```
3번째 줄을 보면 `for` loop 스코프의 `value`가 함수의 파라미터인 `value`를 가리는 문제가 발생합니다.
이 패치는 함수 파라미터의 이름을 `value`에서 `_value`로 바꾸어 문제를 해결합니다.

[pb] Struct.proto 컴파일 오류 수정

---

codegen/ts/messages.ts

```protobuf
syntax = "proto3";
message TestWrapper {
TestInner inner = 1;
}
message TestInner {
int64 data = 1;
}
```
```bash
> import { encodeBinary, getDefaultValue } from './out/messages/TestWrapper'
{}
> encodeBinary(getDefaultValue())
/Users/lucent/pbkit/out/messages/TestInner.ts:16
const tsValue = value.data;
^
Uncaught TypeError: Cannot read property 'data' of undefined
at encodeBinary (/Users/lucent/pbkit/out/messages/TestInner.ts:28:27)
at encodeBinary (/Users/lucent/pbkit/out/messages/TestWrapper.ts:32:75)
at /Users/lucent/pbkit/<repl>.ts:2:32
at Script.runInThisContext (vm.js:134:12)
at exec (/Users/lucent/.nvm/versions/node/v14.17.3/lib/node_modules/ts-node/src/repl.ts:253:17)
at /Users/lucent/.nvm/versions/node/v14.17.3/lib/node_modules/ts-node/src/repl.ts:243:27
at …
```

encodeBinary() 에서 undefined를 인자로 넘기는 문제 수정

---

.github/workflows/pb-build-linux-binary.yml

will be used for aur `pbkit-bin`

add pb build workflow

---

codegen/ts/messages.ts

nested message가 있어 디렉토리가 만들어지는 경우에는 소괄호로 감싸서 디렉토리를 생성해 주도록 하였습니다.  
하지만 메세지가 모두 대문자로 시작하는 것을 전제로 하였기 때문에, 추후 소문자 message에서도 대응이 되도록 수정해야 합니다.

맥/윈도우 파일 시스템이 case-insensitive여서 생기는 디렉토리명 중복 문제 수정

---

codegen/ts/messages.ts

테스트 코드나 storybook 코드를 대체할 때 각 메세지 타입들의 객체를 많이 만들어야 하는데, 이때마다 `...getDefaultValue()` 를 사용하여 기본값을 정해주기가 매우 번거로워 `createValue` 함수를 만들어 대체하도록 했습니다.

Add createValueCode function in message codegen

---

language-server/base-protocol.ts

Web API Headers는 map key의 케이스를 누르는데, vscode-languageserver-node가 case-sensitive한 동작으로 Content-Length를 찾아 에러가 발생합니다.
related to https://github.com/microsoft/vscode-languageserver-node/issues/897

Change Content-Length header name to be case-sensitive

---

core/schema/builder.ts
core/schema/findAllReferences.ts

MessageName 부분에서만 reference 동작이 가능하던 것을 필드 타입에서도 사용할 수 있게끔 수정합니다.

feat(lsp/reference): Allow find typePath from `ast.Type` node

---

codegen/ts/messages.ts

- decodeJson의 repeated field인 경우 value의 유무를 검증하지 않는데, value가 없는 경우 ?? [] 로 fallback되지 못하고 error를 낼 수 있어 optional chaining operator를 추가합니다. https://github.com/pbkit/pbkit/commit/6b692e871daef1be6329ff73f363636bf03a793d
- getDefaultJsonValueToTsValueCode > typePathToCode에서 repeated인 경우 tsType을 기입하지 않아 발생한 문제인데, 실제로 typePathToCode의 인자로 tsType을 context와 다르게 주입해야 하는 경우가 없어 삭제합니다. ba8088a6c5be1d22d5ab07bbb82f6718a1357aee f63eb49
resolves #178

fix(decodeJson): Fix possible / repeated enum bug in decodeJson

---

core/schema/builder.ts
core/schema/findAllReferences.ts
core/schema/gotoDefinition.ts
language-server/json-rpc.ts
language-server/lsp.ts
language-server/server.ts

- lsp.ts를 추가했습니다. → Location, Position, Initialize 관련한 Type들을 모두 옮겼습니다.
- lsp namespace로 사용하게끔 변경하였습니다.
- requestHandler의 return type이 Promise가 아닌 경우에도 대응되도록 변경합니다.

refactor(lsp): Add lsp type definition and apply on request handlers in `server.ts`

---

codegen/ts/messages.ts

- Fix decoding repeated enum field with packed option
```typescript
collection: {
const wireValues = wireMessage.filter(([fieldNumber]) => fieldNumber === 1).map(([, wireValue]) => wireValue);
const value = wireValues.map((wireValue) => wireValue.type === WireType.Varint ? num2name[wireValue.value[0] as keyof typeof num2name] : undefined).filter(x => x !== undefined);
if (!value.length) break collection;
result.babo = value as any;
}
```
```typescript
collection: {
const wireValues = wireMessage.filter(([fieldNumber]) => fieldNumber === 1).map(([, wireValue]) => wireValue);
const value = Array.from(unpackFns.int32(wireValues)).map(num => num2name[num as keyof typeof num2name]);
if (!value.length) break collection;
result.babo = value as any;
}
```
resolve #186

fix(codegen/binary): Fix repeated packed enum decode bug

---

cli/pb/cmds/gen/expandEntryPaths.ts
cli/pollapo/pollapoYml.ts
core/loader/combineLoader.ts
core/loader/deno-fs.ts
core/loader/memoizeLoader.ts
core/schema/builder.ts
language-server/project.ts
language-server/server.ts

When importing the repository's own file in the pollapo package repository, the import path starts from the github repository path(e.g. `username/reponame`).
There is no guarantee that the local directory name matches this, so I made a loader that reads the `repo` field of `pollapo.yml` in the package repository and handles it specially.

language-server - special handling for pollapo repositories

---

codegen/ts/messages.ts

```sh
pb gen ts -o out google/protobuf/map_lite_unittest.proto
```
```sh
diff -u out-before/messages/protobuf_unittest/TestMapLite.ts \
out-after/messages/protobuf_unittest/TestMapLite.ts \
> out.diff
```
```diff
--- out-before/messages/protobuf_unittest/TestMapLite.ts
+++ out-after/messages/protobuf_unittest/TestMapLite.ts
@@ -135,7 +135,7 @@
export function encodeBinary(value: $.protobuf_unittest.TestMapLite): Uint8Array {
const result: WireMessage = [];
{
-    const fields = Object.entries(value.mapInt32Int32);
+    const fields = value.mapInt32Int32.entries();
for (const [key, value] of fields) {
result.push(
[1, { type: WireType.LengthDelimited as const, value: serialize([[1, tsValueToWireValueFns.int32(key)], [2, tsValueToWireValueFns.int32(value)]]) }],
@@ -143,7 +143,7 @@
}
}
{
- …
```

fix codegen bug when generating map field

---

cli/pb/cmds/gen/cmds/swift/index.ts
codegen/swift/index.ts
codegen/swift/services.ts

We provide new two options for generating service codes in swift.
If you want to generate grpc codegen, call `pb gen swift` with `--grpc-service` option.
To generate wrp(webview/worker request protocol) codegen, call with `--wrp-service`.
If you don't provide any service option, no service code will be generated.
You can provide both options together. the generated service codes will be separated. (like `a.grpc.swift`, `a.wrp.swift`)

codegen(swift/wrp): Add codegen for wrp-swift service provider

---

codegen/swift/services.ts

Due to refactoring on wrp-swift, (https://github.com/pbkit/wrp-swift/commit/2d30c469069feee1653c3ba7bfdc2f38b9af1f0d)
- Some symbols have been renamed
- WrpHandlerProvider → WrpServiceProvider
- MethodHandlerContext → WrpRequestContext
- WrpRequestContext → WrpRequestHandlerContext
- WrpServiceHandlerProtocol → WrpRequestHandlerProtocol
- WrpServiceHandler → WrpRequestHandler
- Remove unnecessary access control

refactor(swift/wrp): Apply renamed symbols and some refactoring for swiftformat

---

cli/pollapo/cmds/install.ts
cli/pollapo/pollapoYml.ts

Related issue: #56 
Print `Failed to symlink. Please run the command as administrator.` instead of error message with stack trace

fix: Print error message for symlink failure instead of stack trace

---

cli/pb/cmds/decode/cmds/file-descriptor-set.ts
cli/pb/cmds/decode/index.ts
cli/pb/cmds/gen/cmds/file-descriptor-set.ts
compat/protoc/file-descriptor-set.ts
misc/case.ts

This PR enhances `convertSchemaToFileDescriptorSet`
- Fix values in EnumDescriptor correctly.
- New subcommand 'pb decode file-descriptor-set' for decoding without `google/protobuf/descriptor.proto` in target schema.
- Fix subcommand `pb gen file-descriptor-set --text` to decode FileDescriptorSet correctly when the schema doesn't include `google/protobuf/descriptor.proto`.
- Supports dependencies in FileDescriptor.
- Supports all well-known options for File/Message/Enum/Field.
- Supports Map fields.  
- Supports ServiceDescriptor and MethodDescriptor.
- Pretty-print options when it is empty.
resolves many todos of #140

compat/file-descriptor-set: Enhance `convertSchemaToFileDescriptorSet` 

---

scripts/build-npm-packages/buildCore.ts

- enable ESM options
- use https://github.com/lucacasonato/esbuild_deno_loader for resolving deno HTTP modules.

npm/esbuild: fix esbuild settings

---

cli/pb/cmds/gen/cmds/swift/index.ts
codegen/swift/index.ts
codegen/swift/messages.ts
codegen/swift/services.ts

question: how can we handle the all kinds of paths elegantly? like `~/merong`

swift/codegen: Add exclude-path option for swift codegen

---

compat/buf/workspace.ts
language-server/project.ts

https://docs.buf.build/configuration/v1/buf-work-yaml
프로젝트에 `buf.work.yaml` 파일이 있다면 다른 추가 설정 없이 language server가 똑바로 돌아가게 만들었습니다.

support `buf.work.yaml`

---

codegen/kt/wrp.ts

1. if there is an `java_outer_classname` option, use it (TODO: throw an error on `RealNameOuterClass` is given. protoc does.)
2. check all types'(including service) name if it is same with outer class name regardless of its cases, add `OuterClass` suffix for resolving outer class name.
This issue can be resolved with following steps:
1. rename file name or type name with non-conflict one.
2. add `java_outer_classname` option.

fix(codegen/wrp-kt): fix default outerclass behavior

---

core/parser/proto.regression.test.ts
core/parser/proto.ts

타입명에 group이 포함되는 경우 타입명을 `group` 키워드로 인식하는 문제가 있어 해결합니다.
resolves #246

Fix group keyword parsing logic (#246)

---

misc/github/index.ts

Previously we do not provide detailed response message for `GithubRepoNotFoundError`.

Add response msg for `GithubRepoNotFoundError`

---

codegen/ts/messages.ts

```proto3
syntax = "proto3";
enum A {
DEFAULT = 0;
SOME = 1;
WHY = 2;
}
message B {
optional A a = 1;
optional int32 b = 2;
A c = 3;
int32 d = 4;
}
```
```typescript
export function getDefaultValue(): $.B {
return {
a: undefined,
b: undefined,
c: "DEFAULT",
d: 0,
};
}
```
```typescript
export function getDefaultValue(): $.B {
return {
a: "DEFAULT",
b: 0,
c: "DEFAULT",
d: 0,
};
}
```

ts(codegen): Add support for proto3 optional on getDefaultValue

---

codegen/ts/messages.ts

Use jsonName instead of tsName when json_name option is present on the field. This option is supported on official protobuf implementations.

codegen(ts): support json_name option on encodeJson/decodeJson

---

language-server/json-rpc.ts

- Fix wrong jsonrpc method for logging and sets logging disable by default.
According to the LSP spec, `window/showMessageRequest` and `window/showMessageResponse` are used for displaying message on editor, not for the logging purpose.
This will fix #285 (lsp not working on neovim)

fix(lsp): Fix wrong logging method and set disable by default

---

core/ast/top-level-definitions.ts
core/parser/misc.ts
core/parser/proto.ts
core/visitor/index.ts
language-server/semantic-token-provider.ts

- Change node type of `returns` in Rpc AST to `Keyword`
- Refactor semantic-token-provider and add rpc, scalar type, public/weak import support.
This fix resolves https://github.com/pbkit/vscode-pbkit/issues/22

fix(lsp/semantic-token): Cover more tokens in semantic-token-provider

---

compat/buf/module.ts
language-server/project.ts

Added logic to look for build directories in a `v1beta1` versioned `buf.yaml` files if loading it from a `buf.work.yaml` fails.

Added support for v1beta1 module files (buf.yaml)

---

cli/pollapo/pollapoYml.ts

[`Deno.run` is deprecated](https://deno.land/api@v1.38.5?s=Deno.run ) but [dnt dosen't support `Deno.Command`](https://github.com/denoland/node_shims/issues/110)

use Deno.run instead of Deno.Command

---

cli/pollapo/cmds/install.ts
cli/pollapo/pollapoYml.ts

Added "fetchCommitHashWithGit" to fetch commit hashes from remote repositories.
When the --git option is used, it directly executes git commands for this purpose.

add a function for fetching commit hash with '--git' option
